package cmd

import (
	"fmt"
	"os"

	"github.com/al-Zamakhshari/aman/internal/audit"
	"github.com/al-Zamakhshari/aman/internal/crypto"
	"github.com/spf13/cobra"
)

var memberCmd = &cobra.Command{
	Use:   "member",
	Short: "Manage team members (add, list, remove)",
}

var memberAddCmd = &cobra.Command{
	Use:   "add <name> <pubkey-file>",
	Short: "Register a team member's public key",
	Long: `Adds a team member to the vault registry.

The pubkey file is the .pub file generated by: aman keygen --name <name>

Example:
  aman member add alice alice.pub
  aman member add bob   /path/to/bob.pub`,
	Args: cobra.ExactArgs(2),
	RunE: runMemberAdd,
}

var memberListCmd = &cobra.Command{
	Use:   "list",
	Short: "List registered team members",
	RunE:  runMemberList,
}

var memberRemoveCmd = &cobra.Command{
	Use:   "remove <name>",
	Short: "Remove a team member from the registry",
	Long: `Removes a member from the vault registry.

Note: existing entries encrypted to this member are NOT automatically
re-encrypted. Use 'aman revoke <entry> --from <name>' for each affected entry.`,
	Args: cobra.ExactArgs(1),
	RunE: runMemberRemove,
}

func init() {
	rootCmd.AddCommand(memberCmd)
	memberCmd.AddCommand(memberAddCmd)
	memberCmd.AddCommand(memberListCmd)
	memberCmd.AddCommand(memberRemoveCmd)
}

func runMemberAdd(_ *cobra.Command, args []string) error {
	name := args[0]
	pubFile := args[1]

	v, err := openVault()
	if err != nil {
		return err
	}

	data, err := os.ReadFile(pubFile) //nolint:gosec
	if err != nil {
		return fmt.Errorf("read pubkey file: %w", err)
	}

	bundle, err := crypto.LoadPublicBundle(data)
	if err != nil {
		return fmt.Errorf("parse pubkey: %w", err)
	}

	if err := v.Members.Add(name, bundle); err != nil {
		return err
	}

	v.Audit.Append(audit.Event{Action: "member_add", Actor: name})
	fmt.Printf("✓ Member %q added to vault %q\n", name, v.Cfg.Name)
	return nil
}

func runMemberList(_ *cobra.Command, _ []string) error {
	v, err := openVault()
	if err != nil {
		return err
	}

	names, err := v.Members.List()
	if err != nil {
		return err
	}

	if len(names) == 0 {
		fmt.Println("No members registered. Run: aman member add <name> <pubkey>")
		return nil
	}

	fmt.Printf("Members in vault %q:\n", v.Cfg.Name)
	for _, n := range names {
		fmt.Printf("  • %s\n", n)
	}
	return nil
}

func runMemberRemove(_ *cobra.Command, args []string) error {
	name := args[0]

	v, err := openVault()
	if err != nil {
		return err
	}

	if err := v.Members.Remove(name); err != nil {
		return err
	}

	fmt.Printf("✓ Member %q removed from registry\n", name)
	fmt.Printf("  Remember to revoke their access from individual entries.\n")
	return nil
}
